### ISSUE TITLE
broken link to XDG Base Directory Specification

### ISSUE THREAD

**Issue by milahu** [srstevenson/xdg#111]

**Comment by srstevenson** [comment]
Where's the link you're referring to?

**Comment by milahu** [comment]
in the readme

```md
[spec]:
  https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
```

but now [the link](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is working. probably was a temporary issue at freedesktop.org
