### ISSUE TITLE
purpose of _getenv

### ISSUE THREAD

**Issue by Achimh3011** [srstevenson/xdg#2]
Hi,

just a question: is there a specific reason to implement an own ````_getenv()```` instead of directly using ````os.getenv()````? I cannot find any and I'm wondering whether I miss something obvious.

Thx, Achim.

**Comment by srstevenson** [comment]
It has slightly different behaviour reflecting the parts of the specification like:

> If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used.

`_getenv(varname, default)` returns `default` if `varname` is set but empty (i.e. `os.environ[varname] = ''`), whereas `os.getenv(varname, default)` checks only that the variable is set, not that it's non-empty, so returns an empty string in this case.

**Comment by Achimh3011** [comment]
Understood. Thx.

**Comment by turicas** [comment]
Could also be translated as: `getenv = lambda varname, default: os.environ.get(varname) or default`.

**Comment by srstevenson** [comment]
@turicas: Indeed, thanks!
