### ISSUE TITLE
Module name conflict with pyxdg

### ISSUE THREAD

**Issue by rr-** [srstevenson/xdg#35]
Basically both pyxdg and xdg offer the same module named `xdg`.

This isn't only theoretical problem - software that depends on xdg cannot coexist (without boilerplate) with software that depends on pyxdg. In my specific case, one of the users tried to install [bubblesub](https://github.com/rr-/bubblesub) on Fedora having also installed Blender, which depends on python2-pyxdg. I ended up having hardcoded the xdg paths in my project, but I thought I'd let you know about this issue.

**Comment by srstevenson** [comment]
I'd suggest the `pyxdg` authors use the module name `pyxdg`.

**Comment by rr-** [comment]
Well, their package is older, plus it's pretty nonsensic to use `py` prefix on pypi, which is a package repository made solely for python, don't you think?

**Comment by tblancher** [comment]
I use [goobook](https://aur.archlinux.org/packages/goobook/) which depends on python-xdg in Arch Linux (goobook-git is an AUR package).  I managed to get both python-pyxdg and python-xdg to coexist by creating a venv for python-xdg and installing goobook in it.  This [Arch Linux forum post](https://bbs.archlinux.org/viewtopic.php?id=262403) describes how I did it.

**Comment by mgorny** [comment]
> I'd suggest the `pyxdg` authors use the module name `pyxdg`.

pyxdg dates back to 2011 and has at least a dozen reverse dependencies in Gentoo. Your package comes from 2016 and has literally one revdep (goobook). How does it make sense to modify the older package and require updates to dozen packages just because you thoughtlessly added another package with the same name?

**Comment by srstevenson** [comment]
I've locked this issue due to the use of ad hominems. I welcome technical discussion on this and other issues, but please remain respectful to one another.

**Comment by srstevenson** [comment]
I've commented on https://github.com/srstevenson/xdg/issues/75 to try to renew efforts to find a solution to the namespace collision that doesn't break existing code for either xdg or pyxdg users:

> I've been thinking again about how to resolve this, which is obviously a pain for the users and maintainers of both packages. I met @takluyver, the pyxdg maintainer, in person at a previous PyCon UK, and have no doubt we'd both be willing to implement a solution that fixes the namespace collision whilst avoiding breakage for users of both packages, if such a solution can be found.
>
> Unfortunately, the impasse exists because no such solution has yet been identified. Approaches that have been suggested all break backward compatibility for existing xdg or pyxdg users in some way:
>
> - **Approach**: pyxdg changes namespace to `pyxdg`
>   - ✔️ pyxdg no longer collides with xdg in the `xdg` namespace
>   - ❌ pyxdg users' code is broken if previous pyxdg releases are yanked from PyPI
>   - ❌ if previous pyxdg releases are not yanked from PyPI, the namespace collision remains
> - **Approach**: xdg changes namespace to `xdg_base_directory` or similar
>   - ✔️ xdg no longer collides with pyxdg in the `xdg` namespace
>   - ❌ xdg users' code is broken if previous xdg releases are yanked from PyPI
>   - ❌ if previous xdg releases are not yanked from PyPI, the namespace collision remains
> - **Approach**: merge xdg and pyxdg into a single package whose API is the union of the two original packages in the `xdg` namespace. pyxdg becomes an empty package that just depends on xdg, or xdg becomes an empty package that just depends on pyxdg.
>   - ✔️ pyxdg and xdg no longer collide in the `xdg` namespace
>   - ✔️ users of both packages have a update path that maintains backward compatibility (except for Python 2.7 support, see below)
>   - ❌ pyxdg's code is LGPL licensed, which means some previous users of xdg would not be able to use the unified package ([reference](https://github.com/srstevenson/xdg/issues/83#issuecomment-1039311015))
>   - ❌ Python 2.7 support is lost (which `pyxdg` currently has), as `xdg`'s public API uses Python 3 features such as the `pathlib` module. While there is a backport of `pathlib` to earlier Python versions, this has dropped support for Python 2.7.
>
> Is there a solution that's not been discussed so far, that'll let us move past the impasse without breaking application code for users of either package?

If there are constructive suggestions, let's continue the discussion in #75.
