### ISSUE TITLE
Cannot install xdg with --no-binary :all: flag enabled

### ISSUE THREAD

**Issue by seppeljordan** [srstevenson/xdg#37]
Hi,

I would very much like to use your project but cannot do so.  The reason for this is that `xdg` uses `poetry` as its build tool which does not support installation via `pip` with the `--no-binary :all:` flag option enabled. This is due to a cyclic build dependency on the side of `poetry`.  This makes it impossible to use in cases where building from source is required.  There are reports out there of people who claim that poetry makes packages unusable in contexts like building docker containers from the alpine image or in a homebrew context.  I wanted to ask if there are any plans to use another build system like `setuptools`.

See https://github.com/pypa/pip/issues/5739 and https://github.com/sdispater/poetry/issues/760 for reference on this.

Thanks for doing this project.

**Comment by srstevenson** [comment]
Thanks for raising this, I wasn't aware of the upstream issue. Poetry provides a more convenient development workflow than setuptools, so I don't intend to switch back. Pending this being fixed upstream, are you able to vendor xdg in your own project? (I appreciate this isn't an ultimately ideal solution).

**Comment by seppeljordan** [comment]
Thank you for the feedback.
