### ISSUE TITLE
[Feature Request] Support for XDG User Directories

### ISSUE THREAD

**Issue by nemec** [srstevenson/xdg#45]
It would be helpful to have ready access to the user directories defined by XDG. These variables are stored in a file (location defined in the links below) and normally accessed via the program `xdg-user-dir` (e.g. `xdg-user-dir DOCUMENTS`).

Based on my testing,  it does support arbitrary folders added in the format `XDG_{label}_DIR` after running `xdg-user-dirs-update`, but I personally wouldn't consider it a hard requirement if it's easier to hardcode the default list in the same way you've done the other xdg dirs.

Example contents of `user-dirs.dirs`:
```
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_MUSIC_DIR="$HOME/Music"
...
```

https://www.freedesktop.org/wiki/Software/xdg-user-dirs/
https://wiki.archlinux.org/index.php/XDG_user_directories

**Comment by srstevenson** [comment]
I'm happy to discuss implementations and review patches if anyone wants to implement this.
