### ISSUE TITLE
Relative paths in environment variables should be ignored

### ISSUE THREAD

**Issue by JustAnotherArchivist** [srstevenson/xdg#54]
Per the spec:

> All paths set in these environment variables must be absolute. If an implementation encounters a relative path in any of these variables it should consider the path invalid and ignore it.

As far as I can tell, this package currently takes the values as-is without such validation.

**Comment by srstevenson** [comment]
Thanks for reporting this @JustAnotherArchivist, I'll submit a fix shortly.

**Comment by srstevenson** [comment]
I've just released [5.0.2](https://pypi.org/project/xdg/5.0.2/) to PyPI which fixes this. Thanks again!
